# Generated by Django 4.1.3 on 2022-12-18 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('etapa', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=120)),
                ('is_uxdesigner', models.BooleanField()),
                ('is_uidesigner', models.BooleanField()),
                ('is_uxwriter', models.BooleanField()),
                ('user', models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=120)),
                ('video1', models.CharField(blank=True, max_length=120, null=True)),
                ('video1_about', models.CharField(choices=[('0', 'Research'), ('1', 'Wireframe'), ('2', 'Prototipação'), ('3', 'Write'), ('4', 'Strategy'), ('5', 'Design System')], default='0', max_length=1)),
                ('video2', models.CharField(blank=True, max_length=120, null=True)),
                ('video2_about', models.CharField(choices=[('0', 'Research'), ('1', 'Wireframe'), ('2', 'Prototipação'), ('3', 'Write'), ('4', 'Strategy'), ('5', 'Design System')], default='0', max_length=1)),
                ('video3', models.CharField(blank=True, max_length=120, null=True)),
                ('video3_about', models.CharField(choices=[('0', 'Research'), ('1', 'Wireframe'), ('2', 'Prototipação'), ('3', 'Write'), ('4', 'Strategy'), ('5', 'Design System')], default='0', max_length=1)),
                ('horario_entrev', multiselectfield.db.fields.MultiSelectField(choices=[('1', '8h-12h'), ('2', '13h-17h')], default='0', max_length=30)),
                ('semana_entrev', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta')], default='1', max_length=30)),
                ('talento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='talentos.talento')),
            ],
        ),
    ]
