# Generated by Django 4.1.3 on 2023-01-07 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='link',
        ),
    ]
