# Generated by Django 4.1.3 on 2023-01-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentos', '0002_remove_projeto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talento',
            name='is_uidesigner',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='talento',
            name='is_uxdesigner',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='talento',
            name='is_uxwriter',
            field=models.BooleanField(null=True),
        ),
    ]
